### ISSUE TITLE
Please provide a minor mode (or some other means of enabling coverlay per buffer).

### ISSUE THREAD

**Issue by TauPan** [twada/coverlay.el#10]
Hi!

I like coverlay mode for javascript files, but it only offers a global mode which is superfluous for me in most cases (org files, python files (I use pycoverage for that)). Also it interferes with some of my keybindings (I use C-c C-l for org-insert-link in org files, which is the default binding from org.el). The best solution for my personal taste would be to just enable it for javascript files.

(As a workaround, I'll disable it globally for now and just enable it when I want to see coverage of javascript.)

Thanks!

**Comment by twada** [comment]
Thank you for your suggestion. Since I do not have enough time now so labeled as `help wanted`.

@orzechowskid Thank you for your reaction. Are you interested in enhancing `coverlay.el` ?
