### ISSUE TITLE
Register to MELPA

### ISSUE THREAD

**Issue by twada** [twada/coverlay.el#6]
Register coveray.el to MELPA since version 2.0.0 lands to master.

> As far as i could tell this is the only standalone coverage display for emacs, so it should be useful for a lot of people.
> https://github.com/twada/coverlay.el/pull/5#issuecomment-195920012

> I can do the MELPA part if people have not much time
> https://github.com/twada/coverlay.el/pull/5#issuecomment-195073262

Thank you guys. I need your help.
@FossiFoo @CestDiego

**Comment by twada** [comment]
refs https://github.com/melpa/melpa/pull/3851 (Thanks @kytwb !)

**Comment by kytwb** [comment]
Seems link the keybinding `C-c l` is conflicting thus blocking - see https://github.com/melpa/melpa/pull/3851#issuecomment-217101588. Any candidate for a replacement @twada @FossiFoo?
I personally don't have any preference.

**Comment by twada** [comment]
Now we can install `coverlay` from MELPA.
Thanks @kytwb !
